### ISSUE TITLE
Cannot read sim file

### ISSUE THREAD

**Issue by ppinard** [drix00/pycasinotools#5]
* pycasinotools version: Commit af9a6da300d6231f5a096c167c388693b0f49613
* Python version: 3.5
* Operating System: Linux
* Casino version: 2.5

### Description

I cannot open this sim file with pycasinotools, but it works with Casino.

[VerticalLayers3.sim.zip](https://github.com/drix00/pycasinotools/files/1150490/VerticalLayers3.sim.zip)

### What I Did

I ran:
```python
from casinotools.fileformat.casino2.File import File
f = File()
f.readFromFilepath(filepath)
```

I got the following traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File 
"/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/casino2/File.py", line 39, in readFromFilepath
    self.readFromFileObject(file, isSkipReadingData)
  File "/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/casino2/File.py", line 48, in readFromFileObject
    self._optionSimulationData.read(file)
  File "/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/casino2/SimulationData.py", line 95, in read
    self._read_region_options(file)
  File "/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/casino2/SimulationData.py", line 113, in _read_region_options
    self._region_options.read(file, self._version)
  File "/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/casino2/RegionOptions.py", line 60, in read
    region.read(file, version)
  File "/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/casino2/Region.py", line 103, in read
    element.read(file, self._number_xray_layers, version)
  File "/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/casino2/Element.py", line 161, in read
    self.COUCHE_RADIAL_MV_ABS = self.readDoubleList(file, number_xray_layers)
  File "/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/FileReaderWriterTools.py", line 85, in readDoubleList
    return self._readDoubleListWithoutLoopFast(file, numberElements)
  File "/home/ppinard/documents/workspace/teams/pymontecarlo/pycasinotools/casinotools/fileformat/FileReaderWriterTools.py", line 109, in _readDoubleListWithoutLoopFast
    items = struct.unpack_from(format, buffer)
struct.error: unpack_from requires a buffer of at least 4000 bytes
```

**Comment by drix00** [comment]
Did you generate the file with this version of CASINO or you use the one before:
https://www.dropbox.com/s/l0if2tjngvqk9yc/2017-06-12_19h30m24s_CASINO_v2.5.0.0.zip?dl=0

The problem is pymontecarlo-casino2, use a version without the new intensity, but they are both have the version 2.5.
I will release a new official version as 2.5.1 and update the python script to only read the intensity from this version.

**Comment by drix00** [comment]
I made a new release of CASINO v2.51 with the emitted intensity (in 1/e/sr) and update pycasinotools. You need to download version v2.51 of CASINO to use this feature. A new version of pycasinotools was release on PyPI (0.2.2) from 2e33b42fb7c7629b35f007be5a404fdd1c45c771.

CASINO v2.51 was tested on win XP, Ubuntu, win7 and win10. The results for all of them was read by pycasinotools without problem.

@ppinard test it and if the problem is solve close this issue #5.

**Comment by ppinard** [comment]
Yes the new version solves the problem.
